import { redirect } from 'next/navigation';

// The agent-facing canonical doc is served as raw markdown at /for-agents.md
// (generated by scripts/build-dist.mjs from docs/for-agents-copy.md).
// This route keeps the clean /for-agents URL that llms.txt and the npm
// README advertise.
export function GET() {
  redirect('/for-agents.md');
}
