import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import V4Shell from '@/components/v4/Shell';
import CopyAction from '@/components/v4/CopyAction';
import { AGENT_PROMPT, V4_PACKAGE } from '@/lib/v4-release';
export const metadata: Metadata = { title: 'Typeset.ts for coding agents | Read, compose, verify', description: 'A verifiable typography workflow for coding agents: pinned V4 installation, React-safe ownership, machine-readable capabilities, JSON audits and explicit native fallbacks.', alternates: { canonical: 'https://typeset.us/agents' }, openGraph: { images: ['https://typeset.us/v4/social.png'] } };
const resources = [ ['/for-agents.md','Integration contract'], ['/v4/capabilities.json','Capability manifest'], ['/v4/manifest.json','Pinned release + integrity'], ['/v4/acceptance.json','Release evidence'], ['/v4/SKILL.md','Portable agent skill'], ['/llms.txt','Discovery index'] ];
export default function Agents() {
  return <V4Shell><main id="main" className="v4-main"><header className="v4-doc-hero"><p className="v4-eyebrow">Typeset.ts V4 / For coding agents</p><h1>Good typography.<br />A verifiable workflow.</h1><p>Your agent already builds the layout. Now give it a considered way to finish the text, with clear boundaries and evidence it can inspect.</p></header><div className="v4-document">
    <section><h2>Start with a precise brief.</h2><p>Copy this into your coding agent while working in the client project. It asks for an evaluation first, not a blanket installation.</p><div className="v4-plain-prompt">{AGENT_PROMPT}</div><CopyAction text={AGENT_PROMPT} label="Copy agent prompt" className="v4-button-dark" /></section>
    <section><h2>Everything an agent needs to inspect.</h2><p>Plain Markdown. Versioned JSON. Pinned artifacts. No account, runtime service, tracking pixel, or secret endpoint required by the engine.</p><div className="v4-resource-grid">{resources.map(([href,label])=><a href={href} key={href}>{label}<ArrowUpRight size={18} aria-hidden="true" /></a>)}</div></section>
    <section><h2>One owner. Four decisions.</h2><ol><li><strong>Does composition help?</strong> Capture native layout at the real font and width. Keep native when it is already the better result.</li><li><strong>Who owns rendering?</strong> Use the React adapter for React-managed text. Use the DOM API only for content the framework does not own.</li><li><strong>Did the source and interactions survive?</strong> Compare text, link identity, selection, copying, keyboard focus, resizing, font loading, updates and teardown.</li><li><strong>What did the engine decide?</strong> Report composed and native outcomes separately. An overflow is a hard error; a review item calls for judgment. Never present fallback as perfection.</li></ol></section>
    <section><h2>Install exactly what you evaluated.</h2><div className="v4-code"><pre><code>{`npm install ${V4_PACKAGE}`}</code></pre><CopyAction text={`npm install ${V4_PACKAGE}`} label="Copy pinned installation" /></div><p>The package is the V4 beta distributed from this site. A plain <code>npm install typeset.us</code> still follows the separate V3 npm release. Read the manifest before upgrading.</p><Link className="v4-text-link" href="/v4">Installation, migration and support <ArrowUpRight size={17} aria-hidden="true" /></Link></section>
    <section><h2>Make the result easy to share.</h2><p>A convincing case is a real comparison: unchanged words, the same font and width, and an honest record of what improved. Include a narrow screen, a rich paragraph, and any native fallbacks. Show the evidence, not a universal claim.</p><div className="v4-actions"><CopyAction text="Typeset.ts V4 beta brings markup-aware paragraph composition to the web: links and emphasis intact, React adapters, optional optical hanging and smart quotes, plus a JSON audit for coding agents. Free and MIT licensed. See the live comparison and tested scope: https://typeset.us" label="Copy launch summary" /><a href="/v4/social.png" className="v4-text-link" download>Download launch graphic <ArrowUpRight size={17} aria-hidden="true" /></a></div></section>
  </div></main></V4Shell>;
}
