// @ts-check
// Generated blocks inside hand-written docs. The root README's install lines
// always name the published version (package.json) and its pinned loader's
// integrity (public/sri.json): release-cut rewrites the block at each cut and
// verify-docs fails when it is stale.
const START = '<!-- install:start (generated by release-cut from package.json and public/sri.json; do not edit) -->';
const END = '<!-- install:end -->';

/** @param {string} version @param {string} integrity */
export function rootInstallBlock(version, integrity) {
  return [
    START,
    '```html',
    `<script src="https://typeset.us/go@${version}.js" integrity="${integrity}" crossorigin="anonymous" defer></script>`,
    '```',
    '',
    '```sh',
    `npm i -E typeset.us@${version}`,
    '```',
    END,
  ].join('\n');
}

/**
 * Replace the generated install block in `text`. Throws when the markers are
 * missing, so a cut cannot silently skip it.
 * @param {string} text @param {string} block
 */
export function replaceInstallBlock(text, block) {
  const start = text.indexOf(START), end = text.indexOf(END);
  if (start < 0 || end < start) throw new Error('README.md has no install block markers.');
  return text.slice(0, start) + block + text.slice(end + END.length);
}

/** The block currently in `text`, or null. @param {string} text */
export function currentInstallBlock(text) {
  const start = text.indexOf(START), end = text.indexOf(END);
  return start < 0 || end < start ? null : text.slice(start, end + END.length);
}
