// @ts-check
// The suites test:v4 runs, in order, and where each writes its report.
/** @typedef {{ name: string, report?: string, note?: string, timeout?: number }} Suite */
/** @type {Suite[]} */
export const SUITES = [
  { name: 'verify-ledger', report: 'output/ledger-verification.json', note: 'published artifacts unchanged' },
  { name: 'verify-immutable-4.2', report: 'output/immutable-4.2.json', note: '4.2.0 byte-for-byte' },
  { name: 'verify-ledger-guards', report: 'output/ledger-guards.json', note: 'the ledger catches tampering' },
  { name: 'verify-recipe-reproduces', report: 'output/recipe-reproduces.json', note: 'the 4.2 recipe still rebuilds 4.2.0 byte for byte' },
  { name: 'verify-release-craft', report: 'output/release-craft.json' },
  { name: 'verify-spacing', report: 'output/spacing.json' },
  { name: 'verify-promise', report: 'output/promise.json' },
  { name: 'verify-golden', report: 'output/golden.json', note: 'composition byte-identical to 4.2.0 outside the recorded rendering changes', timeout: 300 },
  { name: 'verify-alignment', report: 'output/alignment.json', note: 'justified text declined as native:justify (C3)' },
  { name: 'verify-keep', report: 'output/keep.json', note: 'the keep option holds phrases together in body text and titles (C14)' },
  { name: 'verify-audit', report: 'output/audit.json', note: 'audit targets resolve; false positives quiet; line-end defects reviewed (C16)' },
  { name: 'verify-acceptance', report: 'output/acceptance.json' },
  { name: 'verify-native-ax', report: 'output/native-ax.json', note: 'engine accessibility trees match the source (C1)' },
  { name: 'verify-break-semantics', report: 'output/break-semantics.json', note: 'generated breaks are word separators; markers paint nothing (C2)' },
  { name: 'verify-strict-csp', report: 'output/strict-csp.json', note: "style-src without 'unsafe-inline' and Trusted Types (C5)" },
  { name: 'verify-copy-privacy', report: 'output/copy-privacy.json', note: 'no hidden content on the clipboard (C11)' },
  { name: 'verify-framework-text', report: 'output/framework-text.json', note: 'framework text updates never show stale text (C6)' },
  { name: 'verify-live-regions', report: 'output/live-regions.json', note: 'live regions are never composed (C4)' },
  { name: 'verify-smart-quotes', report: 'output/smart-quotes.json', note: 'quote education table, server-rendered quotes (C15)' },
  { name: 'verify-inline-code', report: 'output/inline-code-regression.json' },
  { name: 'verify-inline-nowrap', report: 'output/inline-nowrap-regression.json' },
  { name: 'verify-name-groups', report: 'output/name-groups-regression.json' },
  { name: 'verify-wrap-ownership', report: 'output/wrap-ownership-regression.json' },
  { name: 'verify-controller', report: 'output/controller-regression.json' },
  { name: 'verify-mount-ownership', report: 'output/mount-ownership-regression.json' },
  { name: 'verify-iframe-mount', report: 'output/iframe-mount.json', note: 'mount() into a same-origin iframe (C12)' },
  { name: 'verify-recompose-storms', report: 'output/recompose-storms.json', note: 'ancestor mutations recheck a layout key, not recompose (P3)' },
  { name: 'verify-reflow-triggers', report: 'output/reflow-triggers.json', note: 'fonts, spacing overrides and metric transitions recompose (C7)' },
  { name: 'verify-visibility', report: 'output/visibility.json', note: 'hidden text keeps its composition and reveals composed (C8)' },
  { name: 'verify-print-resize', report: 'output/print-resize.json', note: 'no double-wrapped frame in print or while resizing (C9)' },
  { name: 'verify-scheduler', report: 'output/scheduler.json', note: 'busy pages, visible-first work, deferred offscreen resizes (P2)', timeout: 360 },
  { name: 'verify-settle', report: 'output/settle.json', note: 'mount(), go.js and both React adapters settle in shrink-to-fit, grid, table, float, dialog and scroller layouts; smart quotes in every fallback state', timeout: 600 },
  { name: 'verify-translation', report: 'output/translation.json', note: 'composition steps aside for machine translation (C10)' },
  { name: 'verify-options', report: 'output/options.json', note: 'clear errors and development option warnings (K11)' },
  { name: 'verify-react', report: 'output/react.json', note: 'React 18 and 19 adapters in three engines: recomposition, scheduling, lifecycle, API', timeout: 360 },
  { name: 'verify-react-node', report: 'output/react-node.json', note: 'React adapters outside a browser: TypeScript contracts' },
  { name: 'verify-tracking-clipping', report: 'output/tracking-clipping.json' },
  { name: 'verify-loaders', report: 'output/loaders.json' },
  { name: 'verify-fixture-invariants', report: 'output/fixture-invariants.json' },
  { name: 'verify-cli', report: 'output/cli-verification.json' },
  { name: 'verify-site-index', report: 'output/site-index.json', note: 'sri.json lists only immutable pins; cache headers; firewall bypass' },
  { name: 'verify-docs', report: 'output/docs-verification.json', note: 'docs match the code and the release (outcomes, options, install lines, links)' },
  { name: 'verify-release-trust', report: 'output/release-trust.json', note: 'pinned workflows, provenance publishing and the maintainer-published path, SECURITY.md, advisories, release notes' },
  { name: 'verify-package-contents', report: 'output/package-contents.json', note: 'the package the next release would publish' },
  { name: 'verify-budgets', report: 'output/budget-verification.json', note: 'gzip size budgets (runtime budgets: --runtime, nightly)' },
];
