import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowUpRight, Download } from 'lucide-react';
import V4Shell from '@/components/v4/Shell';
import Installer from '@/components/v4/Installer';
import CopyAction from '@/components/v4/CopyAction';
import { V4_BASE, V4_PACKAGE, V4_VERSION } from '@/lib/v4-release';

export const metadata: Metadata = { title: 'Get Typeset.ts V4 | Installation, migration and evidence', description: 'Install Typeset.ts V4 beta with a pinned script, React adapters or DOM API. Read the upgrade guide, support range and measured release evidence.', alternates: { canonical: 'https://typeset.us/v4' }, openGraph: { images: ['https://typeset.us/v4/social.png'] } };
export default function Release() {
  return <V4Shell><main id="main" className="v4-main"><header className="v4-doc-hero"><p className="v4-eyebrow">Typeset.ts / {V4_VERSION} / MIT</p><h1>Get V4.<br />Keep the care.</h1><p>A deliberate upgrade for linked, styled, changing text. Free to use, with an explicit scope and a way to check the result.</p></header>
    <div className="v4-document"><nav className="v4-doc-nav" aria-label="Release sections"><a href="#installation">Install</a><a href="#craft">Craft options</a><a href="#migration">Upgrade from V3</a><a href="#evidence">Evidence and support</a><Link href="/agents">For agents</Link></nav>
      <section id="installation"><h2>Choose your way in.</h2><p className="v4-release-notice"><strong>V4 is an opt-in beta.</strong> The download below is V4. Existing <code>typeset.us/go.js</code> installations and npm V3 are not silently replaced.</p><Installer /><div className="v4-actions"><a className="v4-button" href={V4_PACKAGE}><Download size={17} aria-hidden="true" /> Download V4 package</a><a className="v4-text-link" href="/v4/manifest.json">Checksums and pinned files <ArrowUpRight size={16} aria-hidden="true" /></a></div></section>
      <section id="craft"><h2>The finishing touches are your choice.</h2><p>Composition uses Unicode break opportunities by default. English smart quotes and optical hanging are opt-in. List styling uses a separate stylesheet and real browser markers.</p><div className="v4-code"><pre><code>{`const controller = mount(document, 'article p', {\n  smartQuotes: 'en',\n  opticalHanging: true,\n});\n\n// Optional prose-list styling:\nimport 'typeset.us/styles.css';\nimport { styleProseLists } from 'typeset.us';\nconst lists = styleProseLists(document.querySelector('article'));\n\n// On teardown:\ncontroller.disconnect();\nlists.restore();`}</code></pre></div><p>For rich React text, declare <code>lang="en"</code> when enabling smart quotes. Smart quotes intentionally change displayed and copied punctuation. Hanging is declined in clipping, transformed, indented, or otherwise unsupported layouts.</p></section>
      <section id="migration"><h2>An upgrade, not a surprise.</h2><ol><li><strong>Keep your current pin.</strong> Record your V3 dependency or script URL before changing anything.</li><li><strong>Pick one pilot.</strong> Compare a real article, product description, or document at mobile and desktop widths.</li><li><strong>Choose one owner.</strong> Use V4 React adapters for React text, or scoped V4 DOM mounting elsewhere. Never run V3 and V4 on the same content.</li><li><strong>Verify the interactions.</strong> Check links, selections, copied text, late fonts, content updates, and teardown. Read native reasons and audit review items.</li><li><strong>Keep rollback simple.</strong> Disconnect DOM ownership or unmount the adapter, restore list styling, and return to the previous version.</li></ol><p>The old global and convenience APIs are not a drop-in match. V4 uses <code>window.Typeset</code>, explicit loader scope, and separate composition and craft outcomes.</p><div className="v4-actions"><a className="v4-text-link" href={`${V4_BASE}/MIGRATION.md`}>Full migration guide <ArrowUpRight size={16} aria-hidden="true" /></a><Link className="v4-text-link" href="/install">Legacy V3 platform guides <ArrowUpRight size={16} aria-hidden="true" /></Link></div></section>
      <section id="evidence"><h2>Evidence, with its limits attached.</h2><p>The release is evaluated against real text, captured SceneF failures, adversarial cases, and prior designer comparisons. The approved paragraph policies were preserved for this release.</p><table className="v4-evidence-table"><tbody><tr><th scope="row">Composition</th><td>12,966 comparison/fuzz cases; 1,342 recorded checks including expected-error checks. Unicode conformance is reported separately.</td></tr><tr><th scope="row">Browsers</th><td>Chromium 151, WebKit 26.5, Firefox 151 through local automation. This does not establish historical minimum browser versions.</td></tr><tr><th scope="row">Installation</th><td>Clean Node 22 workflow, installed Next 16.1.6 / React 19.2.3 consumer, matching artifact manifests, ESM and CommonJS core.</td></tr><tr><th scope="row">Clipboard</th><td>84 real macOS browser copy/paste checks, including paragraph boundaries, links and emphasis. Not mobile, Windows, Word or Pages certification.</td></tr><tr><th scope="row">Performance</th><td>120 fresh-page samples across four local configurations. Local budgets passed. CPU throttling is not physical-phone evidence.</td></tr><tr><th scope="row">Still unverified</th><td>Physical iOS/Android, spoken VoiceOver/NVDA behavior, representative-device performance, and remote CI acceptance.</td></tr></tbody></table><p>Supported scope: horizontal LTR Latin prose and titles; declared English, French, German and Spanish; ordinary inline links and emphasis. Unsupported content retains native layout. Extreme text sizes can still expose author-level overflow, which the audit reports rather than disguises.</p><p>The core has no required runtime dependencies or telemetry. The browser global is approximately 34 KB gzip, not the earlier V3 size claim.</p><a className="v4-text-link" href="/v4/acceptance.json">Machine-readable evidence <ArrowUpRight size={16} aria-hidden="true" /></a></section>
      <section><h2>Give your agent a definition of done.</h2><p>An audit pass means a nonempty scope with no hard errors and no unprocessed targets. It does not mean aesthetic perfection or that every paragraph was composed.</p><div className="v4-code"><pre><code>{`npm install -D playwright\nnpx playwright install chromium\nnpx --no-install typeset-audit \\\n  --url http://localhost:3000 \\\n  --selector 'article p'`}</code></pre><CopyAction text={`npm install -D playwright\nnpx playwright install chromium\nnpx --no-install typeset-audit --url http://localhost:3000 --selector 'article p'`} label="Copy audit commands" /></div><p>Read-only by default. <code>--apply</code> changes only an isolated preview, never the deployed site. Reports stay local.</p><Link className="v4-button v4-button-dark" href="/agents">Open the agent workflow <ArrowUpRight size={17} aria-hidden="true" /></Link></section>
    </div></main></V4Shell>;
}
